// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package ugdvesting

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_VestingData           protoreflect.MessageDescriptor
	fd_VestingData_address   protoreflect.FieldDescriptor
	fd_VestingData_amount    protoreflect.FieldDescriptor
	fd_VestingData_start     protoreflect.FieldDescriptor
	fd_VestingData_duration  protoreflect.FieldDescriptor
	fd_VestingData_parts     protoreflect.FieldDescriptor
	fd_VestingData_block     protoreflect.FieldDescriptor
	fd_VestingData_percent   protoreflect.FieldDescriptor
	fd_VestingData_processed protoreflect.FieldDescriptor
	fd_VestingData_cliff     protoreflect.FieldDescriptor
)

func init() {
	file_pax_ugdvesting_vesting_proto_init()
	md_VestingData = File_pax_ugdvesting_vesting_proto.Messages().ByName("VestingData")
	fd_VestingData_address = md_VestingData.Fields().ByName("address")
	fd_VestingData_amount = md_VestingData.Fields().ByName("amount")
	fd_VestingData_start = md_VestingData.Fields().ByName("start")
	fd_VestingData_duration = md_VestingData.Fields().ByName("duration")
	fd_VestingData_parts = md_VestingData.Fields().ByName("parts")
	fd_VestingData_block = md_VestingData.Fields().ByName("block")
	fd_VestingData_percent = md_VestingData.Fields().ByName("percent")
	fd_VestingData_processed = md_VestingData.Fields().ByName("processed")
	fd_VestingData_cliff = md_VestingData.Fields().ByName("cliff")
}

var _ protoreflect.Message = (*fastReflection_VestingData)(nil)

type fastReflection_VestingData VestingData

func (x *VestingData) ProtoReflect() protoreflect.Message {
	return (*fastReflection_VestingData)(x)
}

func (x *VestingData) slowProtoReflect() protoreflect.Message {
	mi := &file_pax_ugdvesting_vesting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_VestingData_messageType fastReflection_VestingData_messageType
var _ protoreflect.MessageType = fastReflection_VestingData_messageType{}

type fastReflection_VestingData_messageType struct{}

func (x fastReflection_VestingData_messageType) Zero() protoreflect.Message {
	return (*fastReflection_VestingData)(nil)
}
func (x fastReflection_VestingData_messageType) New() protoreflect.Message {
	return new(fastReflection_VestingData)
}
func (x fastReflection_VestingData_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_VestingData
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_VestingData) Descriptor() protoreflect.MessageDescriptor {
	return md_VestingData
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_VestingData) Type() protoreflect.MessageType {
	return _fastReflection_VestingData_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_VestingData) New() protoreflect.Message {
	return new(fastReflection_VestingData)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_VestingData) Interface() protoreflect.ProtoMessage {
	return (*VestingData)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_VestingData) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Address != "" {
		value := protoreflect.ValueOfString(x.Address)
		if !f(fd_VestingData_address, value) {
			return
		}
	}
	if x.Amount != int64(0) {
		value := protoreflect.ValueOfInt64(x.Amount)
		if !f(fd_VestingData_amount, value) {
			return
		}
	}
	if x.Start != int64(0) {
		value := protoreflect.ValueOfInt64(x.Start)
		if !f(fd_VestingData_start, value) {
			return
		}
	}
	if x.Duration != int64(0) {
		value := protoreflect.ValueOfInt64(x.Duration)
		if !f(fd_VestingData_duration, value) {
			return
		}
	}
	if x.Parts != int32(0) {
		value := protoreflect.ValueOfInt32(x.Parts)
		if !f(fd_VestingData_parts, value) {
			return
		}
	}
	if x.Block != int64(0) {
		value := protoreflect.ValueOfInt64(x.Block)
		if !f(fd_VestingData_block, value) {
			return
		}
	}
	if x.Percent != int32(0) {
		value := protoreflect.ValueOfInt32(x.Percent)
		if !f(fd_VestingData_percent, value) {
			return
		}
	}
	if x.Processed != false {
		value := protoreflect.ValueOfBool(x.Processed)
		if !f(fd_VestingData_processed, value) {
			return
		}
	}
	if x.Cliff != int32(0) {
		value := protoreflect.ValueOfInt32(x.Cliff)
		if !f(fd_VestingData_cliff, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_VestingData) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "pax.ugdvesting.VestingData.address":
		return x.Address != ""
	case "pax.ugdvesting.VestingData.amount":
		return x.Amount != int64(0)
	case "pax.ugdvesting.VestingData.start":
		return x.Start != int64(0)
	case "pax.ugdvesting.VestingData.duration":
		return x.Duration != int64(0)
	case "pax.ugdvesting.VestingData.parts":
		return x.Parts != int32(0)
	case "pax.ugdvesting.VestingData.block":
		return x.Block != int64(0)
	case "pax.ugdvesting.VestingData.percent":
		return x.Percent != int32(0)
	case "pax.ugdvesting.VestingData.processed":
		return x.Processed != false
	case "pax.ugdvesting.VestingData.cliff":
		return x.Cliff != int32(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pax.ugdvesting.VestingData"))
		}
		panic(fmt.Errorf("message pax.ugdvesting.VestingData does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VestingData) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "pax.ugdvesting.VestingData.address":
		x.Address = ""
	case "pax.ugdvesting.VestingData.amount":
		x.Amount = int64(0)
	case "pax.ugdvesting.VestingData.start":
		x.Start = int64(0)
	case "pax.ugdvesting.VestingData.duration":
		x.Duration = int64(0)
	case "pax.ugdvesting.VestingData.parts":
		x.Parts = int32(0)
	case "pax.ugdvesting.VestingData.block":
		x.Block = int64(0)
	case "pax.ugdvesting.VestingData.percent":
		x.Percent = int32(0)
	case "pax.ugdvesting.VestingData.processed":
		x.Processed = false
	case "pax.ugdvesting.VestingData.cliff":
		x.Cliff = int32(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pax.ugdvesting.VestingData"))
		}
		panic(fmt.Errorf("message pax.ugdvesting.VestingData does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_VestingData) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "pax.ugdvesting.VestingData.address":
		value := x.Address
		return protoreflect.ValueOfString(value)
	case "pax.ugdvesting.VestingData.amount":
		value := x.Amount
		return protoreflect.ValueOfInt64(value)
	case "pax.ugdvesting.VestingData.start":
		value := x.Start
		return protoreflect.ValueOfInt64(value)
	case "pax.ugdvesting.VestingData.duration":
		value := x.Duration
		return protoreflect.ValueOfInt64(value)
	case "pax.ugdvesting.VestingData.parts":
		value := x.Parts
		return protoreflect.ValueOfInt32(value)
	case "pax.ugdvesting.VestingData.block":
		value := x.Block
		return protoreflect.ValueOfInt64(value)
	case "pax.ugdvesting.VestingData.percent":
		value := x.Percent
		return protoreflect.ValueOfInt32(value)
	case "pax.ugdvesting.VestingData.processed":
		value := x.Processed
		return protoreflect.ValueOfBool(value)
	case "pax.ugdvesting.VestingData.cliff":
		value := x.Cliff
		return protoreflect.ValueOfInt32(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pax.ugdvesting.VestingData"))
		}
		panic(fmt.Errorf("message pax.ugdvesting.VestingData does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VestingData) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "pax.ugdvesting.VestingData.address":
		x.Address = value.Interface().(string)
	case "pax.ugdvesting.VestingData.amount":
		x.Amount = value.Int()
	case "pax.ugdvesting.VestingData.start":
		x.Start = value.Int()
	case "pax.ugdvesting.VestingData.duration":
		x.Duration = value.Int()
	case "pax.ugdvesting.VestingData.parts":
		x.Parts = int32(value.Int())
	case "pax.ugdvesting.VestingData.block":
		x.Block = value.Int()
	case "pax.ugdvesting.VestingData.percent":
		x.Percent = int32(value.Int())
	case "pax.ugdvesting.VestingData.processed":
		x.Processed = value.Bool()
	case "pax.ugdvesting.VestingData.cliff":
		x.Cliff = int32(value.Int())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pax.ugdvesting.VestingData"))
		}
		panic(fmt.Errorf("message pax.ugdvesting.VestingData does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VestingData) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "pax.ugdvesting.VestingData.address":
		panic(fmt.Errorf("field address of message pax.ugdvesting.VestingData is not mutable"))
	case "pax.ugdvesting.VestingData.amount":
		panic(fmt.Errorf("field amount of message pax.ugdvesting.VestingData is not mutable"))
	case "pax.ugdvesting.VestingData.start":
		panic(fmt.Errorf("field start of message pax.ugdvesting.VestingData is not mutable"))
	case "pax.ugdvesting.VestingData.duration":
		panic(fmt.Errorf("field duration of message pax.ugdvesting.VestingData is not mutable"))
	case "pax.ugdvesting.VestingData.parts":
		panic(fmt.Errorf("field parts of message pax.ugdvesting.VestingData is not mutable"))
	case "pax.ugdvesting.VestingData.block":
		panic(fmt.Errorf("field block of message pax.ugdvesting.VestingData is not mutable"))
	case "pax.ugdvesting.VestingData.percent":
		panic(fmt.Errorf("field percent of message pax.ugdvesting.VestingData is not mutable"))
	case "pax.ugdvesting.VestingData.processed":
		panic(fmt.Errorf("field processed of message pax.ugdvesting.VestingData is not mutable"))
	case "pax.ugdvesting.VestingData.cliff":
		panic(fmt.Errorf("field cliff of message pax.ugdvesting.VestingData is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pax.ugdvesting.VestingData"))
		}
		panic(fmt.Errorf("message pax.ugdvesting.VestingData does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_VestingData) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "pax.ugdvesting.VestingData.address":
		return protoreflect.ValueOfString("")
	case "pax.ugdvesting.VestingData.amount":
		return protoreflect.ValueOfInt64(int64(0))
	case "pax.ugdvesting.VestingData.start":
		return protoreflect.ValueOfInt64(int64(0))
	case "pax.ugdvesting.VestingData.duration":
		return protoreflect.ValueOfInt64(int64(0))
	case "pax.ugdvesting.VestingData.parts":
		return protoreflect.ValueOfInt32(int32(0))
	case "pax.ugdvesting.VestingData.block":
		return protoreflect.ValueOfInt64(int64(0))
	case "pax.ugdvesting.VestingData.percent":
		return protoreflect.ValueOfInt32(int32(0))
	case "pax.ugdvesting.VestingData.processed":
		return protoreflect.ValueOfBool(false)
	case "pax.ugdvesting.VestingData.cliff":
		return protoreflect.ValueOfInt32(int32(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pax.ugdvesting.VestingData"))
		}
		panic(fmt.Errorf("message pax.ugdvesting.VestingData does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_VestingData) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in pax.ugdvesting.VestingData", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_VestingData) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VestingData) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_VestingData) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_VestingData) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*VestingData)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Address)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Amount != 0 {
			n += 1 + runtime.Sov(uint64(x.Amount))
		}
		if x.Start != 0 {
			n += 1 + runtime.Sov(uint64(x.Start))
		}
		if x.Duration != 0 {
			n += 1 + runtime.Sov(uint64(x.Duration))
		}
		if x.Parts != 0 {
			n += 1 + runtime.Sov(uint64(x.Parts))
		}
		if x.Block != 0 {
			n += 1 + runtime.Sov(uint64(x.Block))
		}
		if x.Percent != 0 {
			n += 1 + runtime.Sov(uint64(x.Percent))
		}
		if x.Processed {
			n += 2
		}
		if x.Cliff != 0 {
			n += 1 + runtime.Sov(uint64(x.Cliff))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*VestingData)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Cliff != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Cliff))
			i--
			dAtA[i] = 0x48
		}
		if x.Processed {
			i--
			if x.Processed {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x40
		}
		if x.Percent != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Percent))
			i--
			dAtA[i] = 0x38
		}
		if x.Block != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Block))
			i--
			dAtA[i] = 0x30
		}
		if x.Parts != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Parts))
			i--
			dAtA[i] = 0x28
		}
		if x.Duration != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Duration))
			i--
			dAtA[i] = 0x20
		}
		if x.Start != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Start))
			i--
			dAtA[i] = 0x18
		}
		if x.Amount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Amount))
			i--
			dAtA[i] = 0x10
		}
		if len(x.Address) > 0 {
			i -= len(x.Address)
			copy(dAtA[i:], x.Address)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Address)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*VestingData)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VestingData: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VestingData: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Address = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
				}
				x.Amount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Amount |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
				}
				x.Start = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Start |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
				}
				x.Duration = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Duration |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Parts", wireType)
				}
				x.Parts = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Parts |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
				}
				x.Block = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Block |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Percent", wireType)
				}
				x.Percent = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Percent |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Processed", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.Processed = bool(v != 0)
			case 9:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Cliff", wireType)
				}
				x.Cliff = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Cliff |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: pax/ugdvesting/vesting.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VestingData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount    int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Start     int64  `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`       // Use timestamp type if you want to store it as a timestamp
	Duration  int64  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"` // Duration in seconds
	Parts     int32  `protobuf:"varint,5,opt,name=parts,proto3" json:"parts,omitempty"`
	Block     int64  `protobuf:"varint,6,opt,name=block,proto3" json:"block,omitempty"`
	Percent   int32  `protobuf:"varint,7,opt,name=percent,proto3" json:"percent,omitempty"`
	Processed bool   `protobuf:"varint,8,opt,name=processed,proto3" json:"processed,omitempty"`
	Cliff     int32  `protobuf:"varint,9,opt,name=cliff,proto3" json:"cliff,omitempty"`
}

func (x *VestingData) Reset() {
	*x = VestingData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pax_ugdvesting_vesting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VestingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VestingData) ProtoMessage() {}

// Deprecated: Use VestingData.ProtoReflect.Descriptor instead.
func (*VestingData) Descriptor() ([]byte, []int) {
	return file_pax_ugdvesting_vesting_proto_rawDescGZIP(), []int{0}
}

func (x *VestingData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VestingData) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *VestingData) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *VestingData) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VestingData) GetParts() int32 {
	if x != nil {
		return x.Parts
	}
	return 0
}

func (x *VestingData) GetBlock() int64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *VestingData) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *VestingData) GetProcessed() bool {
	if x != nil {
		return x.Processed
	}
	return false
}

func (x *VestingData) GetCliff() int32 {
	if x != nil {
		return x.Cliff
	}
	return 0
}

var File_pax_ugdvesting_vesting_proto protoreflect.FileDescriptor

var file_pax_ugdvesting_vesting_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x61, 0x78, 0x2f, 0x75, 0x67, 0x64, 0x76, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2f, 0x76, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x70, 0x61, 0x78, 0x2e, 0x75, 0x67, 0x64, 0x76, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x22, 0xeb,
	0x01, 0x0a, 0x0b, 0x56, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x69, 0x66, 0x66, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6c, 0x69, 0x66, 0x66, 0x42, 0x9c, 0x01, 0x0a,
	0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x78, 0x2e, 0x75, 0x67, 0x64, 0x76, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x42, 0x0c, 0x56, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x1f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69,
	0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x61, 0x78, 0x2f, 0x75, 0x67, 0x64, 0x76, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0xa2, 0x02, 0x03, 0x50, 0x55, 0x58, 0xaa, 0x02, 0x0e, 0x50, 0x61, 0x78,
	0x2e, 0x55, 0x67, 0x64, 0x76, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0xca, 0x02, 0x0e, 0x50, 0x61,
	0x78, 0x5c, 0x55, 0x67, 0x64, 0x76, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0xe2, 0x02, 0x1a, 0x50,
	0x61, 0x78, 0x5c, 0x55, 0x67, 0x64, 0x76, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0f, 0x50, 0x61, 0x78, 0x3a,
	0x3a, 0x55, 0x67, 0x64, 0x76, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pax_ugdvesting_vesting_proto_rawDescOnce sync.Once
	file_pax_ugdvesting_vesting_proto_rawDescData = file_pax_ugdvesting_vesting_proto_rawDesc
)

func file_pax_ugdvesting_vesting_proto_rawDescGZIP() []byte {
	file_pax_ugdvesting_vesting_proto_rawDescOnce.Do(func() {
		file_pax_ugdvesting_vesting_proto_rawDescData = protoimpl.X.CompressGZIP(file_pax_ugdvesting_vesting_proto_rawDescData)
	})
	return file_pax_ugdvesting_vesting_proto_rawDescData
}

var file_pax_ugdvesting_vesting_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pax_ugdvesting_vesting_proto_goTypes = []interface{}{
	(*VestingData)(nil), // 0: pax.ugdvesting.VestingData
}
var file_pax_ugdvesting_vesting_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pax_ugdvesting_vesting_proto_init() }
func file_pax_ugdvesting_vesting_proto_init() {
	if File_pax_ugdvesting_vesting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pax_ugdvesting_vesting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VestingData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pax_ugdvesting_vesting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pax_ugdvesting_vesting_proto_goTypes,
		DependencyIndexes: file_pax_ugdvesting_vesting_proto_depIdxs,
		MessageInfos:      file_pax_ugdvesting_vesting_proto_msgTypes,
	}.Build()
	File_pax_ugdvesting_vesting_proto = out.File
	file_pax_ugdvesting_vesting_proto_rawDesc = nil
	file_pax_ugdvesting_vesting_proto_goTypes = nil
	file_pax_ugdvesting_vesting_proto_depIdxs = nil
}
